const canvas = document.querySelector('#arena');
const ctx = canvas.getContext('2d');
const mapCanvas = document.querySelector('#map');
const mapCtx = mapCanvas.getContext('2d');
const crosshair = document.querySelector('.crosshair');
const adminPanel = document.querySelector('#admin-panel');
const ui = { wave: document.querySelector('#wave'), score: document.querySelector('#score'), high: document.querySelector('#high-score'), ammo: document.querySelector('#ammo'), health: document.querySelector('#health-bar'), threats: document.querySelector('#threat-count'), distance: document.querySelector('#distance'), salvage: document.querySelector('#salvage'), relics: document.querySelector('#relics'), objective: document.querySelector('#objective-text'), start: document.querySelector('#start-screen'), over: document.querySelector('#game-over'), final: document.querySelector('#final-score'), announcement: document.querySelector('#biome-announcement') };
const keys = {}; const pointer = { x: 0, y: 0, down: false }; let animation; let lastTime = 0; let adminMode = true;
const beaconRegionRadius = 1200;
const mapRadius = 18000;
const sectorRegions = [
  [{ name: 'TOXIC MARSH', color: '#65b49a', dark: '#172d2d' }, { name: 'SCORCHED WASTES', color: '#ff865c', dark: '#3b211d' }, { name: 'FROZEN PEAKS', color: '#9fd8e3', dark: '#1b2a3c' }, { name: 'ASHEN LOWLANDS', color: '#c88968', dark: '#322522' }],
  [{ name: 'THUNDER PLAINS', color: '#f2c96d', dark: '#302b1f' }, { name: 'IRONWOOD', color: '#8fc47e', dark: '#1d3026' }, { name: 'GLASS DESERT', color: '#e889b4', dark: '#34202d' }, { name: 'FROSTFALL TRENCH', color: '#82c5d7', dark: '#1b2e3b' }],
  [{ name: 'BONE ORCHARD', color: '#d7b07a', dark: '#352b25' }, { name: 'EMBER SEA', color: '#ff725e', dark: '#3b201d' }, { name: 'BLACKROOT WILDS', color: '#8fcf9d', dark: '#1c3026' }, { name: 'GRAVITY FIELDS', color: '#b69be8', dark: '#29233b' }],
  [{ name: 'STORM CITADEL', color: '#8db7ee', dark: '#202d45' }, { name: 'CRIMSON CHASM', color: '#ef6672', dark: '#3b2029' }, { name: 'NULL ICE', color: '#a9e3e6', dark: '#1c3338' }, { name: 'WRAITH MOOR', color: '#a88fd0', dark: '#292238' }],
  [{ name: 'SUNLESS VALE', color: '#bd9f7a', dark: '#30271f' }, { name: 'STARFIRE RIDGE', color: '#ff9b62', dark: '#3c251d' }, { name: 'DYING NEBULA', color: '#d58ee0', dark: '#34213b' }, { name: 'ABYSSAL SHELF', color: '#709ed0', dark: '#1d2c45' }],
  [{ name: 'VOID RIFT', color: '#ca8bea', dark: '#281b39' }, { name: 'EVENT HORIZON', color: '#ec7dc4', dark: '#3b1d35' }, { name: 'DEAD STAR', color: '#ffb067', dark: '#3b281e' }, { name: 'INFINITE DARK', color: '#809eea', dark: '#202744' }]
];
const biomes = sectorRegions[0];
let game = freshGame();
function freshGame() { return { active: false, score: 0, high: Number(localStorage.getItem('horde-high') || 0), wave: 1, currentSector: 1, health: 100, ammo: 12, salvage: 0, relics: 0, banked: Number(localStorage.getItem('horde-salvage') || 0), enemies: [], bullets: [], sparks: [], gems: [], nodes: [], discovered: new Set(['sanctuary']), player: { x: 0, y: 0, angle: 0 }, spawnTimer: 0, fireTimer: 0, pulseTimer: 0, biomeKey: null, announcementTimer: 0, camera: { x: 0, y: 0 } }; }
ui.high.textContent = String(game.high).padStart(6, '0');
function resize() { const ratio = window.devicePixelRatio || 1; canvas.width = canvas.clientWidth * ratio; canvas.height = canvas.clientHeight * ratio; ctx.setTransform(ratio, 0, 0, ratio, 0, 0); if (!game.active) game.player = { x: canvas.clientWidth / 2, y: canvas.clientHeight / 2, angle: 0 }; }
window.addEventListener('resize', resize); resize();
window.addEventListener('keydown', event => { keys[event.key.toLowerCase()] = true; if (event.key === 'F2') { event.preventDefault(); adminMode = !adminMode; adminPanel.hidden = !adminMode; } if (event.key === ' ' && game.active) shoot(); if (event.key.toLowerCase() === 'q' && game.active) pulse(); }); window.addEventListener('keyup', event => keys[event.key.toLowerCase()] = false);
canvas.addEventListener('pointermove', event => { const box = canvas.getBoundingClientRect(); pointer.x = event.clientX - box.left; pointer.y = event.clientY - box.top; crosshair.style.left = `${pointer.x}px`; crosshair.style.top = `${pointer.y}px`; }); canvas.addEventListener('pointerdown', () => { pointer.down = true; if (game.active) shoot(); }); window.addEventListener('pointerup', () => pointer.down = false);
document.querySelector('#start-button').onclick = start; document.querySelector('#restart-button').onclick = start; adminPanel.hidden = !adminMode; adminPanel.querySelectorAll('[data-admin]').forEach(button => button.addEventListener('click', event => { event.preventDefault(); event.stopPropagation(); adminAction(button.dataset.admin, button.dataset.value); }));
function adminAction(action, value) { if (!game.active) start(); if (action === 'sector') teleportToSector(Number(value)); if (action === 'spawn') for (let i = 0; i < 20; i++) spawn(); if (action === 'refill') { game.health = 100; game.ammo = 12; game.salvage = 0; game.relics = 0; } if (action === 'reset') { teleportPlayer(0, 0); game.enemies = []; game.bullets = []; game.discovered = new Set(['sanctuary']); game.biomeKey = null; } }
function teleportToSector(sector) { teleportPlayer((sector - .5) * 3000, 0); game.currentSector = sector; game.biomeKey = null; game.discovered.add(getSectorKey(sector - 1)); }
function teleportPlayer(x, y) { game.player.x = x; game.player.y = y; game.camera.x = x; game.camera.y = y; }
function start() { game = freshGame(); game.active = true; for (let i = 0; i < 140; i++) game.nodes.push({ x: (Math.random() - .5) * mapRadius * 2, y: (Math.random() - .5) * mapRadius * 1.5, type: Math.random() > .82 ? 'relic' : 'scrap', taken: false }); ui.start.classList.add('hidden'); ui.over.classList.add('hidden'); lastTime = performance.now(); cancelAnimationFrame(animation); animation = requestAnimationFrame(loop); }
function shoot() { if (!game.active || game.fireTimer > 0 || game.ammo <= 0) return; const p = game.player; game.ammo--; game.fireTimer = 145; game.bullets.push({ x: p.x + Math.cos(p.angle) * 20, y: p.y + Math.sin(p.angle) * 20, vx: Math.cos(p.angle) * 650, vy: Math.sin(p.angle) * 650, life: .7 }); for (let i = 0; i < 4; i++) game.sparks.push({ x: p.x + Math.cos(p.angle) * 25, y: p.y + Math.sin(p.angle) * 25, life: .2, vx: Math.cos(p.angle) * 100 + (Math.random() - .5) * 100, vy: Math.sin(p.angle) * 100 + (Math.random() - .5) * 100 }); }
function pulse() { if (game.pulseTimer > 0) return; game.pulseTimer = 7; game.enemies.forEach(e => { if (Math.hypot(e.x - game.player.x, e.y - game.player.y) < 170) { e.hp = 0; game.score += 50; burst(e.x, e.y, 8, 180); } }); burst(game.player.x, game.player.y, 35, 260); }
function spawn() { const angle = Math.random() * Math.PI * 2; const radius = Math.max(canvas.clientWidth, canvas.clientHeight) * .72; game.enemies.push({ x: game.player.x + Math.cos(angle) * radius, y: game.player.y + Math.sin(angle) * radius, r: 10 + Math.random() * 6, speed: 38 + game.currentSector * 10 + Math.random() * 22, hp: 1 }); }
function loop(now) { const dt = Math.min((now - lastTime) / 1000, .04); lastTime = now; update(dt); updateBiomeAnnouncement(dt); draw(); drawMap(); if (game.active) animation = requestAnimationFrame(loop); }
function updateBiomeAnnouncement(dt) { const biome = getBiome(game.player.x, game.player.y); game.discovered.add(biome.key === 'sanctuary' ? 'sanctuary' : getSectorKey(Math.min(sectorRegions.length - 1, Math.floor(Math.hypot(game.player.x, game.player.y) / 3000)))); if (biome.key !== game.biomeKey) { game.biomeKey = biome.key; game.announcementTimer = 3; announceBiome(biome); } game.announcementTimer = Math.max(0, game.announcementTimer - dt); if (game.announcementTimer === 0) ui.announcement.classList.remove('show'); }
function update(dt) { const p = game.player; const dx = (keys.d ? 1 : 0) - (keys.a ? 1 : 0); const dy = (keys.s ? 1 : 0) - (keys.w ? 1 : 0); const length = Math.hypot(dx, dy) || 1; p.x += dx / length * (keys.shift ? 390 : 220) * dt; p.y += dy / length * (keys.shift ? 390 : 220) * dt; p.angle = Math.atan2(pointer.y - canvas.clientHeight / 2, pointer.x - canvas.clientWidth / 2); game.camera.x += (p.x - game.camera.x) * Math.min(1, dt * 7); game.camera.y += (p.y - game.camera.y) * Math.min(1, dt * 7); const distance = Math.hypot(p.x, p.y); const safe = distance < beaconRegionRadius; game.currentSector = Math.min(sectorRegions.length, Math.floor(distance / 3000) + 1); const biome = getBiome(p.x, p.y); game.fireTimer = Math.max(0, game.fireTimer - dt * 1000); game.pulseTimer = Math.max(0, game.pulseTimer - dt); if (pointer.down) shoot(); if (game.ammo === 0 && game.fireTimer === 0) game.ammo = 12; if (safe) { game.health = Math.min(100, game.health + 15 * dt); if (game.salvage || game.relics) { game.banked += game.salvage + game.relics * 5; game.salvage = 0; game.relics = 0; localStorage.setItem('horde-salvage', game.banked); } }
  game.spawnTimer -= dt; const target = safe ? 0 : 5 + game.currentSector * 3 + Math.floor(distance / 260); if (game.spawnTimer <= 0 && game.enemies.length < Math.min(100, target)) { spawn(); game.spawnTimer = Math.max(.12, .8 - game.currentSector * .025 - distance / 4000); } game.bullets.forEach(b => { b.x += b.vx * dt; b.y += b.vy * dt; b.life -= dt; }); game.bullets = game.bullets.filter(b => b.life > 0); game.enemies.forEach(e => { const angle = Math.atan2(p.y - e.y, p.x - e.x); e.x += Math.cos(angle) * e.speed * dt; e.y += Math.sin(angle) * e.speed * dt; if (Math.hypot(p.x - e.x, p.y - e.y) < e.r + 12) game.health -= 28 * dt; });
  game.bullets.forEach(b => game.enemies.forEach(e => { if (e.hp && Math.hypot(b.x - e.x, b.y - e.y) < e.r + 5) { e.hp = 0; b.life = 0; game.score += 100; if (Math.random() > .72) game.gems.push({ x: e.x, y: e.y, life: 18 }); burst(e.x, e.y, 8, 170); } })); game.enemies = game.enemies.filter(e => e.hp > 0); game.gems.forEach(g => { const angle = Math.atan2(p.y - g.y, p.x - g.x); if (Math.hypot(p.x - g.x, p.y - g.y) < 130) { g.x += Math.cos(angle) * 190 * dt; g.y += Math.sin(angle) * 190 * dt; } g.life -= dt; if (Math.hypot(p.x - g.x, p.y - g.y) < 18) { game.salvage++; g.life = 0; } }); game.gems = game.gems.filter(g => g.life > 0); game.nodes.forEach(n => { if (!n.taken && Math.hypot(p.x - n.x, p.y - n.y) < 22) { n.taken = true; n.type === 'relic' ? game.relics++ : game.salvage += 3; burst(n.x, n.y, 14, 150); } }); game.sparks.forEach(s => { s.x += s.vx * dt; s.y += s.vy * dt; s.life -= dt; }); game.sparks = game.sparks.filter(s => s.life > 0); if (game.score >= game.wave * 1200) game.wave++; updateUI(distance, safe, biome); if (game.health <= 0) end(); }
function getSectorKey(sector) { return `sector-${sector}`; }
function getBiome(x, y) { if (Math.hypot(x, y) < beaconRegionRadius) return { name: 'BEACON SANCTUARY', color: '#f9c779', dark: '#172d2d', key: 'sanctuary', animationKey: 'sanctuary' }; const angle = (Math.atan2(y, x) + Math.PI * 2) % (Math.PI * 2); const index = Math.floor(angle / (Math.PI / 2)); const sector = Math.min(sectorRegions.length - 1, Math.floor(Math.hypot(x, y) / 3000)); const biome = sectorRegions[sector][index]; return { ...biome, key: `sector-${sector}-${index}`, sectorKey: getSectorKey(sector), animationKey: `biome-${index}` }; }
function getDiscoveryKey(x, y) { const biome = getBiome(x, y); return biome.key === 'sanctuary' ? 'sanctuary' : biome.sectorKey; }
function announceBiome(biome) { ui.announcement.textContent = biome.name; ui.announcement.style.color = biome.color; ui.announcement.className = `biome-announcement show ${biome.animationKey}`; }
function burst(x, y, amount, force) { for (let i = 0; i < amount; i++) game.sparks.push({ x, y, life: .45, vx: (Math.random() - .5) * force, vy: (Math.random() - .5) * force }); }
function updateUI(distance, safe, biome) { const sector = Math.floor(distance / 3000) + 1; ui.wave.textContent = String(sector).padStart(2, '0'); ui.score.textContent = String(game.score).padStart(6, '0'); ui.ammo.textContent = game.ammo; ui.health.style.width = `${Math.max(0, game.health)}%`; ui.threats.textContent = String(game.enemies.length).padStart(2, '0'); ui.distance.textContent = `${String(Math.floor(distance / 10)).padStart(3, '0')}m`; ui.salvage.textContent = String(game.salvage).padStart(2, '0'); ui.relics.textContent = String(game.relics).padStart(2, '0'); ui.objective.textContent = safe ? 'SANCTUARY // SALVAGE BANKED' : 'RETURN TO BEACON // SALVAGE'; }
function end() { game.active = false; game.high = Math.max(game.high, game.score); localStorage.setItem('horde-high', game.high); ui.final.textContent = String(game.score).padStart(6, '0'); ui.high.textContent = String(game.high).padStart(6, '0'); ui.over.classList.remove('hidden'); }
function drawMap() { const w = mapCanvas.width, h = mapCanvas.height, scale = w / (mapRadius * 2); mapCtx.clearRect(0, 0, w, h); mapCtx.fillStyle = "#100d13"; mapCtx.fillRect(0, 0, w, h); mapCtx.save(); mapCtx.translate(w / 2, h / 2); mapCtx.scale(scale, scale); sectorRegions.forEach((regions, sector) => { const radius = (sector + 1) * 3000; mapCtx.strokeStyle = `${regions[0].color}99`; mapCtx.lineWidth = 3 / scale; mapCtx.beginPath(); mapCtx.arc(0, 0, radius, 0, Math.PI * 2); mapCtx.stroke(); }); mapCtx.strokeStyle = "#f9c779"; mapCtx.lineWidth = 7 / scale; mapCtx.beginPath(); mapCtx.arc(0, 0, beaconRegionRadius, 0, Math.PI * 2); mapCtx.stroke(); game.nodes.forEach(node => { if (!node.taken) { mapCtx.fillStyle = node.type === "relic" ? "#b9f4ff" : "#ffbe68"; mapCtx.fillRect(node.x - 30, node.y - 30, 60, 60); } }); game.enemies.forEach(enemy => { mapCtx.fillStyle = "#ff4d42"; mapCtx.fillRect(enemy.x - 35, enemy.y - 35, 70, 70); }); mapCtx.fillStyle = "#100d13ee"; mapCtx.fillRect(-mapRadius, -mapRadius, mapRadius * 2, mapRadius * 2); game.discovered.forEach(key => { if (key === "sanctuary") { mapCtx.fillStyle = "#f9c77933"; mapCtx.beginPath(); mapCtx.arc(0, 0, beaconRegionRadius, 0, Math.PI * 2); mapCtx.fill(); } else { const sector = Number(key.split("-")[1]); const inner = sector * 3000; const outer = (sector + 1) * 3000; mapCtx.fillStyle = `${sectorRegions[sector][0].color}28`; mapCtx.beginPath(); mapCtx.arc(0, 0, outer, 0, Math.PI * 2); mapCtx.arc(0, 0, inner, 0, Math.PI * 2, true); mapCtx.fill(); } }); game.nodes.forEach(node => { if (!node.taken && game.discovered.has(getDiscoveryKey(node.x, node.y))) { mapCtx.fillStyle = node.type === "relic" ? "#b9f4ff" : "#ffbe68"; mapCtx.fillRect(node.x - 30, node.y - 30, 60, 60); } }); game.enemies.forEach(enemy => { if (game.discovered.has(getDiscoveryKey(enemy.x, enemy.y))) { mapCtx.fillStyle = "#ff4d42"; mapCtx.fillRect(enemy.x - 35, enemy.y - 35, 70, 70); } }); mapCtx.fillStyle = "#f9c779"; mapCtx.beginPath(); mapCtx.arc(0, 0, 70, 0, Math.PI * 2); mapCtx.fill(); mapCtx.fillStyle = "#ffffff"; mapCtx.beginPath(); mapCtx.arc(game.player.x, game.player.y, 90, 0, Math.PI * 2); mapCtx.fill(); mapCtx.restore(); }
function draw() { const w = canvas.clientWidth, h = canvas.clientHeight, biome = getBiome(game.player.x, game.player.y); ctx.clearRect(0, 0, w, h); ctx.fillStyle = biome.dark; ctx.fillRect(0, 0, w, h); const camX = game.camera.x - w / 2, camY = game.camera.y - h / 2; ctx.save(); ctx.translate(-camX, -camY); ctx.strokeStyle = `${biome.color}18`; for (let x = -mapRadius; x < mapRadius; x += 160) { ctx.beginPath(); ctx.moveTo(x, -mapRadius); ctx.lineTo(x, mapRadius); ctx.stroke(); } for (let y = -mapRadius; y < mapRadius; y += 160) { ctx.beginPath(); ctx.moveTo(-mapRadius, y); ctx.lineTo(mapRadius, y); ctx.stroke(); } [beaconRegionRadius, 3000, 6000, 9500, 13000].forEach((radius, i) => { ctx.strokeStyle = i === 0 ? '#f9c77999' : `${biome.color}28`; ctx.setLineDash(i ? [12, 20] : []); ctx.beginPath(); ctx.arc(0, 0, radius, 0, Math.PI * 2); ctx.stroke(); }); ctx.setLineDash([]); ctx.lineWidth = 3; ctx.strokeStyle = `${biome.color}55`; [0, Math.PI / 2, Math.PI, Math.PI * 1.5].forEach(angle => { ctx.beginPath(); ctx.moveTo(0, 0); ctx.lineTo(Math.cos(angle) * mapRadius, Math.sin(angle) * mapRadius); ctx.stroke(); }); ctx.setLineDash([]); ctx.setLineDash([]); game.nodes.forEach(n => { if (n.taken) return; ctx.fillStyle = n.type === 'relic' ? '#b9f4ff' : '#ffbe68'; ctx.shadowBlur = 14; ctx.shadowColor = ctx.fillStyle; ctx.beginPath(); ctx.arc(n.x, n.y, n.type === 'relic' ? 7 : 5, 0, Math.PI * 2); ctx.fill(); ctx.shadowBlur = 0; }); game.gems.forEach(g => { ctx.fillStyle = '#ffcc70'; ctx.beginPath(); ctx.moveTo(g.x, g.y - 5); ctx.lineTo(g.x + 5, g.y); ctx.lineTo(g.x, g.y + 5); ctx.lineTo(g.x - 5, g.y); ctx.fill(); }); game.sparks.forEach(s => { ctx.fillStyle = `rgba(255,${100 + s.life * 200},70,${s.life * 4})`; ctx.fillRect(s.x, s.y, 3, 3); }); game.bullets.forEach(b => { ctx.fillStyle = '#ffd08a'; ctx.beginPath(); ctx.arc(b.x, b.y, 3, 0, Math.PI * 2); ctx.fill(); }); game.enemies.forEach(e => { ctx.save(); ctx.translate(e.x, e.y); ctx.rotate(Math.atan2(game.player.y - e.y, game.player.x - e.x)); ctx.fillStyle = biome.color; ctx.beginPath(); ctx.moveTo(e.r + 4, 0); ctx.lineTo(-e.r, -e.r); ctx.lineTo(-e.r * .55, 0); ctx.lineTo(-e.r, e.r); ctx.closePath(); ctx.fill(); ctx.restore(); }); ctx.strokeStyle = '#f9c779'; ctx.lineWidth = 3; ctx.beginPath(); ctx.arc(0, 0, 35, 0, Math.PI * 2); ctx.stroke(); ctx.fillStyle = '#f9c779'; ctx.beginPath(); ctx.arc(0, 0, 12, 0, Math.PI * 2); ctx.fill(); const p = game.player; ctx.save(); ctx.translate(p.x, p.y); ctx.rotate(p.angle); ctx.fillStyle = '#e9dfd2'; ctx.beginPath(); ctx.arc(0, 0, 13, 0, Math.PI * 2); ctx.fill(); ctx.fillStyle = '#ffb35c'; ctx.fillRect(5, -3, 22, 6); ctx.fillStyle = '#3f2630'; ctx.beginPath(); ctx.arc(0, 0, 7, 0, Math.PI * 2); ctx.fill(); ctx.restore(); ctx.restore(); }